const technologies = [
  'React',
  'React Hooks',
  'Redux',
  'Redux Toolkit',
  'RTK',
  'Next.js',
  'Next.js 13',
  'TypeScript',
  'JavaScript',
  'CSS',
  'SASS/SCSS',
  'HTML5',
  'Tailwind',
  'Material UI',
  'Chakra UI',
  'CSS-in-JS',
  'REST API',
  'Axios',
  'Firebase',
  'Cloud Firestore',
  'Mongo',
  'MongoDB',
  'MongoDB Atlas',
  'Webpack',
  'Microsoft Bot Framework',
  'Microsoft Azure',
  'Tanstack/React Query',
  'Styled System',
  'Bootstrap',
  'Gulp',
  'Parcel',
  'Git',
  'GitHub',
  'GitBash',
  'styled-components',
  '@emotion',
  'formik',
  'yup',
  'swiper',
  'chart.js',
  'nodemailer',
  'handlebars',
  'bcrypt',
  'notiflix',
  'toastify',
  'lodash',
];

export default technologies;
